language: c
sudo: required
env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "Mbtc2+vR9I7lPZYEG5lGDJyfWQ3+RGqg0Eq2E0jAzpcjJRmwoUn6l/nDbMsp83HrKE7u9z5iZaweIQemYBDkvNDiuPuD8cDLeQwts5pSCL5dHD8zxtCKtyixzGPv2H+zrUUDI6YytCJ5lTr98keBX3HkCqhsvWeagPfQ5S1Re1E7GuZQZWbW2O/OSHQtSKfBxSeVyIhR4VrY2RHw+tNt7B4Ic3XORiAqL+h3fKpvEYOqIfIcaZsjURAkA+zEu8OfsPgmmjM6MUmLaWFOmkkUV3guzB/Q/hZuuDSmChcVHzR2dT4DqVJqnOd6iSoKnTk0Na1S81e6V2GdUjGBbVxGgpxTmLrNxw1ljDz/7WuZGkfQzlMDv35phOCqX6cmi4iVTkpjbxVbieKeNorWQBXSRFdRlcO8mJE5DoEsfKzGXgCigAEYu9UHmJFXeLmUBUmpcZz+6bvDtuX2nLk3ZBu8V3fpkVBl9LEYj1UKNTek1L6ogjlZ7zWVM71XrcG8ZpXJVdgnig7ybizf4g/wEpzuusJ5ZlFGuTqye+DmbI4KzhQO69f4EjFMLXQbI9HLLvDMF/KGydiNSrumduUTJn/Szwp4YZX1fqG5ElpXUx5ZVjOdxerlNakwzLlImuSLx9VYsp2gvoYNMVpd0FpHdlY4I0W+4TlynF0kO2Ov6uOrC4o="
cache:
  directories:
    - /var/cache/apt/
    - /var/cache/pbuilder/aptcache/


matrix:
  include:

   # ###### Ubuntu Linux ####################################################

   # ====== Ubuntu 20.04 (Focal Fossa) ======================================
   - name: "Ubuntu 20.04 (Focal Fossa) with GCC"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="ubuntu:focal" VARIANT="ubuntu" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
   - name: "Ubuntu 20.04 (Focal Fossa) with Clang"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="ubuntu:focal" VARIANT="ubuntu" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
   - name: "Ubuntu 20.04 (Focal Fossa) packaging with pbuilder"
     dist: focal
     group: travis_latest
     env: DOCKER="ubuntu:focal" VARIANT="ubuntu" TOOL="pbuilder"

   # ====== Ubuntu 19.10 (Eoan Ermine) ======================================
   - name: "Ubuntu 19.10 (Eoan Ermine) with GCC"
     os: linux
     dist: bionic
     group: travis_latest
     env: DOCKER="ubuntu:eoan" VARIANT="ubuntu" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
   - name: "Ubuntu 19.10 (Eoan Ermine) with Clang"
     os: linux
     dist: bionic
     group: travis_latest
     env: DOCKER="ubuntu:eoan" VARIANT="ubuntu" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
   - name: "Ubuntu 19.10 (Eoan Ermine) packaging with pbuilder"
     dist: bionic
     group: travis_latest
     env: DOCKER="ubuntu:eoan" VARIANT="ubuntu" TOOL="pbuilder"

   # ====== Ubuntu 18.04 (Bionic Beaver) ====================================
   - name: "Ubuntu 18.04 (Bionic Beaver) with GCC"
     os: linux
     dist: bionic
     group: travis_latest
     env: DOCKER="ubuntu:bionic" VARIANT="ubuntu" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
   - name: "Ubuntu 18.04 (Bionic Beaver) with Clang"
     os: linux
     dist: bionic
     group: travis_latest
     env: DOCKER="ubuntu:bionic" VARIANT="ubuntu" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
   - name: "Ubuntu 18.04 (Bionic Beaver) packaging with pbuilder"
     os: linux
     dist: bionic
     group: travis_latest
     env: DOCKER="ubuntu:bionic" VARIANT="ubuntu" TOOL="pbuilder"

   # ====== Ubuntu 16.04 (Xenial Xerus) =====================================
   - name: "Ubuntu 16.04 (Xenial Xerus) with GCC"
     os: linux
     dist: bionic
     group: travis_latest
     env: DOCKER="ubuntu:xenial" VARIANT="ubuntu" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
   - name: "Ubuntu 16.04 (Xenial Xerus) with Clang"
     os: linux
     dist: bionic
     group: travis_latest
     env: DOCKER="ubuntu:xenial" VARIANT="ubuntu" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
   - name: "Ubuntu 16.04 (Xenial Xerus) packaging with pbuilder"
     os: linux
     dist: bionic
     group: travis_latest
     env: DOCKER="ubuntu:xenial" VARIANT="ubuntu" TOOL="pbuilder"

   # ====== Ubuntu 14.04 (Trusty Tahr) ======================================
   - name: "Ubuntu 14.04 (Trusty Tahr) with GCC"
     os: linux
     dist: bionic
     group: travis_latest
     env: DOCKER="ubuntu:trusty" VARIANT="ubuntu" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
   - name: "Ubuntu 14.04 (Trusty Tahr) with Clang"
     os: linux
     dist: bionic
     group: travis_latest
     env: DOCKER="ubuntu:trusty" VARIANT="ubuntu" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
   - name: "Ubuntu 14.04 (Trusty Tahr) packaging with pbuilder"
     os: linux
     dist: bionic
     group: travis_latest
     env: DOCKER="ubuntu:trusty" VARIANT="ubuntu" TOOL="pbuilder"


    # ###### Debian Linux ###################################################

    # ====== Debian Testing =================================================
   - name: "Debian Testing with GCC"
     os: linux
     dist: bionic
     group: travis_latest
     env: DOCKER="debian:testing" VARIANT="debian" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
   - name: "Debian Testing with Clang"
     os: linux
     dist: bionic
     group: travis_latest
     env: DOCKER="debian:testing" VARIANT="debian" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
   - name: "Debian Testing packaging with pbuilder"
     os: linux
     dist: bionic
     group: travis_latest
     env: DOCKER="debian:testing" VARIANT="debian" TOOL="pbuilder"

   # ====== Debian Sid ======================================================
   - name: "Debian Sid with GCC"
     os: linux
     dist: bionic
     group: travis_latest
     env: DOCKER="debian:sid" VARIANT="debian" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
   - name: "Debian Sid with Clang"
     os: linux
     dist: bionic
     group: travis_latest
     env: DOCKER="debian:sid" VARIANT="debian" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
   - name: "Debian Sid packaging with pbuilder"
     os: linux
     dist: bionic
     group: travis_latest
     env: DOCKER="debian:sid" VARIANT="debian" TOOL="pbuilder"

   # ====== Debian Buster ===================================================
   - name: "Debian Buster with GCC"
     os: linux
     dist: bionic
     group: travis_latest
     env: DOCKER="debian:buster" VARIANT="debian" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
   - name: "Debian Buster with Clang"
     os: linux
     dist: bionic
     group: travis_latest
     env: DOCKER="debian:buster" VARIANT="debian" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
   - name: "Debian Buster packaging with pbuilder"
     os: linux
     dist: bionic
     group: travis_latest
     env: DOCKER="debian:buster" VARIANT="debian" TOOL="pbuilder"

   # ====== Debian Stretch ==================================================
   - name: "Debian Stretch with GCC"
     os: linux
     dist: bionic
     group: travis_latest
     env: DOCKER="debian:stretch" VARIANT="debian" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
   - name: "Debian Stretch with Clang"
     os: linux
     dist: bionic
     group: travis_latest
     env: DOCKER="debian:stretch" VARIANT="debian" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
   - name: "Debian Stretch packaging with pbuilder"
     os: linux
     dist: bionic
     group: travis_latest
     env: DOCKER="debian:stretch" VARIANT="debian" TOOL="pbuilder"


   # ###### Fedora Linux ####################################################

   # ====== Fedora 31 =======================================================
   - name: "Fedora 31 with GCC"
     os: linux
     dist: bionic
     group: travis_latest
     env: DOCKER="fedora:31" VARIANT="fedora" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
   - name: "Fedora 31 with Clang"
     os: linux
     dist: bionic
     group: travis_latest
     env: DOCKER="fedora:31" VARIANT="fedora" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
   - name: "Fedora 31 packaging with mock"
     os: linux
     dist: bionic
     group: travis_latest
     env: DOCKER="fedora:31" VARIANT="fedora" TOOL="mock"

   # ====== Fedora 32 =======================================================
   - name: "Fedora 32 with GCC"
     os: linux
     dist: bionic
     group: travis_latest
     env: DOCKER="fedora:32" VARIANT="fedora" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
   - name: "Fedora 32 with Clang"
     os: linux
     dist: bionic
     group: travis_latest
     env: DOCKER="fedora:32" VARIANT="fedora" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
   - name: "Fedora 32 packaging with mock"
     os: linux
     dist: bionic
     group: travis_latest
     env: DOCKER="fedora:32" VARIANT="fedora" TOOL="mock"

   ## ====== Fedora Rawhide ==================================================
   #- name: "Fedora Rawhide with GCC"
     #os: linux
     #dist: bionic
     #group: travis_latest
     #env: DOCKER="fedora:rawhide" VARIANT="fedora" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
   #- name: "Fedora Rawhide with Clang"
     #os: linux
     #dist: bionic
     #group: travis_latest
     #env: DOCKER="fedora:rawhide" VARIANT="fedora" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
   #- name: "Fedora Rawhide packaging with mock"
     #os: linux
     #dist: bionic
     #group: travis_latest
     #env: DOCKER="fedora:rawhide" VARIANT="fedora" TOOL="mock"


   # ###### FreeBSD #########################################################

   # ====== FreeBSD 12.1-RELEASE ============================================
   - name: "FreeBSD 12.1-RELEASE with Clang"
     os: linux
     dist: bionic
     group: travis_latest
     env: QEMU="FreeBSD" VARIANT="12.1-RELEASE" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
   - name: "FreeBSD 12.1-RELEASE with GCC"
     os: linux
     dist: bionic
     group: travis_latest
     env: QEMU="FreeBSD" VARIANT="12.1-RELEASE" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"

   # ====== FreeBSD 12.0-RELEASE ============================================
   - name: "FreeBSD 12.0-RELEASE with Clang"
     os: linux
     dist: bionic
     group: travis_latest
     env: QEMU="FreeBSD" VARIANT="12.0-RELEASE" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
   - name: "FreeBSD 12.0-RELEASE with GCC"
     os: linux
     dist: bionic
     group: travis_latest
     env: QEMU="FreeBSD" VARIANT="12.0-RELEASE" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"

   # ====== FreeBSD 11.3-RELEASE ============================================
   - name: "FreeBSD 11.3-RELEASE with Clang"
     os: linux
     dist: bionic
     group: travis_latest
     env: QEMU="FreeBSD" VARIANT="11.3-RELEASE" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
   - name: "FreeBSD 11.3-RELEASE with GCC"
     os: linux
     dist: bionic
     group: travis_latest
     env: QEMU="FreeBSD" VARIANT="11.3-RELEASE" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"


   # ###### Other ###########################################################

   # ====== MacOS X ========================================================
   # - name: "MacOS X"
   #   os: osx
   #   osx_image: xcode9.4
   #   compiler: clang
   #   group: travis_latest


   # ###### Special #########################################################

   - name: "Default Build"
     os: linux
     dist: bionic
     group: travis_latest
     env: TOOL="compile"

   - name: "Coverity Scan"
     os: linux
     dist: bionic
     group: travis_latest
     env:
      - TOOL="coverity"
      - VARIANT="ubuntu"
      - COVERITY_PROJECT="dreibh%2Fsctplib"
      - COVERITY_SCAN_NOTIFICATION_EMAIL="dreibh@simula.no"
      - COVERITY_SCAN_BRANCH="coverity_scan"


before_install:
  - ci/before-install

install:
  - ci/install

script:
  - ci/build
  - ci/test
