#!/bin/sh -x

rm -rf admin
mkdir admin

if command -v glibtoolize >/dev/null ; then
   glibtoolize --force
elif command -v libtoolize >/dev/null ; then
   libtoolize --force
else
   echo >&2 "ERROR: Cannot find libtoolize or glibtoolize!"
   exit 1
fi

aclocal
autoheader
automake --gnu --add-missing --copy
autoconf
