#!/bin/bash
# $Id$
# --------------------------------------------------------------------------
#
#              //===//   //=====   //===//   //       //   //===//
#             //    //  //        //    //  //       //   //    //
#            //===//   //=====   //===//   //       //   //===<<
#           //   \\         //  //        //       //   //    //
#          //     \\  =====//  //        //=====  //   //===//    Version II
#
# ------------- An Efficient RSerPool Prototype Implementation -------------
#
# Copyright (C) 2002-2007 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@iem.uni-due.de


. ./debian.conf


# Nur einmalig erforderlich!
# dh_make -c gpl -n -e dreibh@iem.uni-due.de -m


DISTRIBUTIONS=`\
( \
while [ x$1 != "x" ] ; do \
   echo $1 && \
   shift ; \
done \
) | sort -u`
if [ "$DISTRIBUTIONS" == "" ] ; then
   DISTRIBUTIONS="default"
fi


rm -f $PACKAGE-*.gz $PACKAGE"_"*.gz
( ./bootstrap && ./configure $CONFOPT && make dist ) || exit 1


for DISTRIBUTION in $DISTRIBUTIONS ; do

   VERSION=`ls $PACKAGE-*.gz|sed -e "s/$PACKAGE-//g" -e "s/.tar.gz//g"` && \
   rm -rf $PACKAGE-$VERSION $PACKAGE-$VERSION.orig && \
   tar xzf $INPUT/$PACKAGE-$VERSION.tar.gz && \
   cp -r $PACKAGE-$VERSION $PACKAGE-$VERSION.orig && \
   cd $PACKAGE-$VERSION && \
   cp -r $INPUT/debian . && \
   rm -rf debian/.svn || exit


   if [ "$DISTRIBUTION" != "default" ] ; then
      sed -e "s/) hardy;/$DISTRIBUTION) $DISTRIBUTION;/g" <debian/changelog >debian/changelog.new
      mv debian/changelog.new debian/changelog
   fi


   # Ohne Signatur!
   # debuild -us -uc
   # Für Sources:
   # debuild -S
   # Für Binaries:
   # debuild -b

   # Mit Signatur!
   debuild -sa -S -k'Thomas Dreibholz <dreibh@iem.uni-due.de>'


   # Wichtig: In /etc/pbuilderrc COMPONENTS="main universe" setzen!
   # Wichtig: Jetzt Update mit Option "--override-config"!
   # sudo pbuilder update --override-config

   cd ..
done
